@startuml LandCal
class ILandTaxCal <<interface>>

ILandTaxCal <|-down- landTaxCal_1216
ILandTaxCal <|-down- landTaxCal_0706

LandExcel *-up- LandCal
LandConfiguration *-up- LandCal
LandTaxCal *-up- LandCal
LandTaxCal --* ILandTaxCal

@enduml
